openapi: 3.0.3
info:
  title: OpenRating API
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /health:
    get:
      summary: Liveness probe
      responses:
        '200':
          description: OK
  /v1/players:
    post:
      summary: Create a player
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayerUpsert'
      responses:
        '200':
          description: Player created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerResponse'
    get:
      summary: List players for an organization
      parameters:
        - in: query
          name: organization_id
          schema: { type: string }
          required: true
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 200
        - in: query
          name: cursor
          schema: { type: string }
        - in: query
          name: q
          schema: { type: string }
      responses:
        '200':
          description: Paginated list of players
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerListResponse'
  /v1/matches:
    post:
      summary: Submit a match result and update ratings
      parameters:
        - in: header
          name: Idempotency-Key
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatchSubmit'
      responses:
        '200':
          description: Match processed with rating deltas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchSubmitResponse'
    get:
      summary: List matches for an organization
      parameters:
        - in: query
          name: organization_id
          schema: { type: string }
          required: true
        - in: query
          name: sport
          schema: { type: string }
        - in: query
          name: player_id
          schema: { type: string }
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 200
        - in: query
          name: cursor
          schema: { type: string }
        - in: query
          name: start_after
          schema: { type: string, format: date-time }
        - in: query
          name: start_before
          schema: { type: string, format: date-time }
      responses:
        '200':
          description: Paginated list of matches
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchListResponse'
components:
  schemas:
    PlayerUpsert:
      type: object
      required: [organization_id, display_name]
      properties:
        organization_id: { type: string }
        display_name: { type: string }
        short_name: { type: string }
        native_name: { type: string }
        external_ref: { type: string }
        given_name: { type: string }
        family_name: { type: string }
        sex: { type: string, enum: [M, F, X] }
        birth_year: { type: integer }
        country_code: { type: string }
        region_id: { type: string }
    PlayerResponse:
      type: object
      properties:
        player_id: { type: string }
        organization_id: { type: string }
        display_name: { type: string }
        short_name: { type: string, nullable: true }
        native_name: { type: string, nullable: true }
        given_name: { type: string, nullable: true }
        family_name: { type: string, nullable: true }
        sex: { type: string, enum: [M, F, X], nullable: true }
        birth_year: { type: integer, nullable: true }
        country_code: { type: string, nullable: true }
        region_id: { type: string, nullable: true }
        external_ref: { type: string, nullable: true }
    PlayerListResponse:
      type: object
      properties:
        players:
          type: array
          items:
            $ref: '#/components/schemas/PlayerResponse'
        next_cursor: { type: string, nullable: true }
    MatchSubmit:
      type: object
      required: [provider_id, organization_id, discipline, format, start_time, sides, games]
      properties:
        provider_id: { type: string }
        organization_id: { type: string }
        discipline: { type: string, enum: [SINGLES, DOUBLES, MIXED] }
        format: { type: string, example: BO3_21RALLY }
        start_time: { type: string, format: date-time }
        venue_region_id: { type: string }
        tier: { type: string, enum: [SANCTIONED, LEAGUE, SOCIAL, EXHIBITION] }
        sides:
          type: object
          properties:
            A:
              type: object
              properties:
                players:
                  type: array
                  minItems: 1
                  maxItems: 2
                  items: { type: string }
            B:
              type: object
              properties:
                players:
                  type: array
                  minItems: 1
                  maxItems: 2
                  items: { type: string }
        games:
          type: array
          items:
            type: object
            properties:
              game_no: { type: integer }
              a: { type: integer }
              b: { type: integer }
    MatchSubmitResponse:
      type: object
      properties:
        match_id: { type: string }
        ratings:
          type: array
          items:
            type: object
            properties:
              player_id: { type: string }
              mu_before: { type: number }
              mu_after: { type: number }
              delta: { type: number }
              sigma_after: { type: number }
              win_probability_pre: { type: number }
    MatchListResponse:
      type: object
      properties:
        matches:
          type: array
          items:
            $ref: '#/components/schemas/MatchSummary'
        next_cursor: { type: string, nullable: true }
    MatchSummary:
      type: object
      properties:
        match_id: { type: string }
        organization_id: { type: string }
        sport: { $ref: '#/components/schemas/MatchSubmit/properties/sport' }
        discipline: { $ref: '#/components/schemas/MatchSubmit/properties/discipline' }
        format: { type: string }
        tier: { type: string, nullable: true }
        start_time: { type: string, format: date-time }
        venue_id: { type: string, nullable: true }
        region_id: { type: string, nullable: true }
        sides:
          type: object
          additionalProperties:
            type: object
            properties:
              players:
                type: array
                items: { type: string }
        games:
          type: array
          items:
            type: object
            properties:
              game_no: { type: integer }
              a: { type: integer }
              b: { type: integer }
