export const P = {
  baseMu: 1500,
  baseSigma: 300,
  sigmaProvisional: 130,
  beta: 185,
  K0: 44,
  sigmaRef: 200,
  KBounds: { min: 8, max: 60 },
  sigmaMin: 70,
  sigmaMax: 350,
  etaDown: 0.1,
  etaUp: 0.09,
  surpriseThreshold: 0.3,
  rookieBoostMatches: 20,
  rookieKMultiplier: 1.8,
  multiplierCap: 1.5,
  mov:
    {
      rally: { min: 0.7, max: 1.3, capPerGame: 11 },
      set: { min: 0.85, max: 1.15, capPerSet: 3 },
    },
  tierWeights: {
    SANCTIONED: 1.15,
    LEAGUE: 1.05,
    SOCIAL: 1.0,
    EXHIBITION: 0.9,
    DEFAULT: 1.0,
  } as Record<string, number>,
  mismatchLambda: 0.35,
  idle: { ratePerWeek: 0.0075, activationDays: 28 },
  sexOffsets: {
    enabled: true,
    baseline: 'M',
    kFactor: 12,
    deltaMax: 6,
    maxAbs: 120,
    regularization: 0.01,
    minEdges90d: 200,
    maxCiWidth: 40,
  },
  synergy: {
    K0: 6,
    gammaMin: -40,
    gammaMax: 40,
    deltaMax: 2,
    activationMatches: 3,
    decayRatePerWeek: 0.03,
    regularization: 0.02,
  },
  graph: {
    smoothingLambda: 0.02,
    horizonDays: 30,
  },
  drift: {
    targetStd: 200,
    maxDailyDelta: 60,
  },
  region: {
    maxShiftPerDay: 8,
  },
};
